package com.caner.sketchweather

/** [şekil * 8 + stil] -> 10 hava ikonu; son satır Gerçekçi set. */
object IconTable {
    val ROWS = arrayOf(
        intArrayOf(R.drawable.i_a1_sun, R.drawable.i_a1_moon, R.drawable.i_a1_partly, R.drawable.i_a1_partly_night, R.drawable.i_a1_cloud, R.drawable.i_a1_fog, R.drawable.i_a1_drizzle, R.drawable.i_a1_rain, R.drawable.i_a1_snow, R.drawable.i_a1_storm),
        intArrayOf(R.drawable.i_a2_sun, R.drawable.i_a2_moon, R.drawable.i_a2_partly, R.drawable.i_a2_partly_night, R.drawable.i_a2_cloud, R.drawable.i_a2_fog, R.drawable.i_a2_drizzle, R.drawable.i_a2_rain, R.drawable.i_a2_snow, R.drawable.i_a2_storm),
        intArrayOf(R.drawable.i_a3_sun, R.drawable.i_a3_moon, R.drawable.i_a3_partly, R.drawable.i_a3_partly_night, R.drawable.i_a3_cloud, R.drawable.i_a3_fog, R.drawable.i_a3_drizzle, R.drawable.i_a3_rain, R.drawable.i_a3_snow, R.drawable.i_a3_storm),
        intArrayOf(R.drawable.i_a4_sun, R.drawable.i_a4_moon, R.drawable.i_a4_partly, R.drawable.i_a4_partly_night, R.drawable.i_a4_cloud, R.drawable.i_a4_fog, R.drawable.i_a4_drizzle, R.drawable.i_a4_rain, R.drawable.i_a4_snow, R.drawable.i_a4_storm),
        intArrayOf(R.drawable.i_a5_sun, R.drawable.i_a5_moon, R.drawable.i_a5_partly, R.drawable.i_a5_partly_night, R.drawable.i_a5_cloud, R.drawable.i_a5_fog, R.drawable.i_a5_drizzle, R.drawable.i_a5_rain, R.drawable.i_a5_snow, R.drawable.i_a5_storm),
        intArrayOf(R.drawable.i_a6_sun, R.drawable.i_a6_moon, R.drawable.i_a6_partly, R.drawable.i_a6_partly_night, R.drawable.i_a6_cloud, R.drawable.i_a6_fog, R.drawable.i_a6_drizzle, R.drawable.i_a6_rain, R.drawable.i_a6_snow, R.drawable.i_a6_storm),
        intArrayOf(R.drawable.i_a7_sun, R.drawable.i_a7_moon, R.drawable.i_a7_partly, R.drawable.i_a7_partly_night, R.drawable.i_a7_cloud, R.drawable.i_a7_fog, R.drawable.i_a7_drizzle, R.drawable.i_a7_rain, R.drawable.i_a7_snow, R.drawable.i_a7_storm),
        intArrayOf(R.drawable.i_a8_sun, R.drawable.i_a8_moon, R.drawable.i_a8_partly, R.drawable.i_a8_partly_night, R.drawable.i_a8_cloud, R.drawable.i_a8_fog, R.drawable.i_a8_drizzle, R.drawable.i_a8_rain, R.drawable.i_a8_snow, R.drawable.i_a8_storm),
        intArrayOf(R.drawable.i_b1_sun, R.drawable.i_b1_moon, R.drawable.i_b1_partly, R.drawable.i_b1_partly_night, R.drawable.i_b1_cloud, R.drawable.i_b1_fog, R.drawable.i_b1_drizzle, R.drawable.i_b1_rain, R.drawable.i_b1_snow, R.drawable.i_b1_storm),
        intArrayOf(R.drawable.i_b2_sun, R.drawable.i_b2_moon, R.drawable.i_b2_partly, R.drawable.i_b2_partly_night, R.drawable.i_b2_cloud, R.drawable.i_b2_fog, R.drawable.i_b2_drizzle, R.drawable.i_b2_rain, R.drawable.i_b2_snow, R.drawable.i_b2_storm),
        intArrayOf(R.drawable.i_b3_sun, R.drawable.i_b3_moon, R.drawable.i_b3_partly, R.drawable.i_b3_partly_night, R.drawable.i_b3_cloud, R.drawable.i_b3_fog, R.drawable.i_b3_drizzle, R.drawable.i_b3_rain, R.drawable.i_b3_snow, R.drawable.i_b3_storm),
        intArrayOf(R.drawable.i_b4_sun, R.drawable.i_b4_moon, R.drawable.i_b4_partly, R.drawable.i_b4_partly_night, R.drawable.i_b4_cloud, R.drawable.i_b4_fog, R.drawable.i_b4_drizzle, R.drawable.i_b4_rain, R.drawable.i_b4_snow, R.drawable.i_b4_storm),
        intArrayOf(R.drawable.i_b5_sun, R.drawable.i_b5_moon, R.drawable.i_b5_partly, R.drawable.i_b5_partly_night, R.drawable.i_b5_cloud, R.drawable.i_b5_fog, R.drawable.i_b5_drizzle, R.drawable.i_b5_rain, R.drawable.i_b5_snow, R.drawable.i_b5_storm),
        intArrayOf(R.drawable.i_b6_sun, R.drawable.i_b6_moon, R.drawable.i_b6_partly, R.drawable.i_b6_partly_night, R.drawable.i_b6_cloud, R.drawable.i_b6_fog, R.drawable.i_b6_drizzle, R.drawable.i_b6_rain, R.drawable.i_b6_snow, R.drawable.i_b6_storm),
        intArrayOf(R.drawable.i_b7_sun, R.drawable.i_b7_moon, R.drawable.i_b7_partly, R.drawable.i_b7_partly_night, R.drawable.i_b7_cloud, R.drawable.i_b7_fog, R.drawable.i_b7_drizzle, R.drawable.i_b7_rain, R.drawable.i_b7_snow, R.drawable.i_b7_storm),
        intArrayOf(R.drawable.i_b8_sun, R.drawable.i_b8_moon, R.drawable.i_b8_partly, R.drawable.i_b8_partly_night, R.drawable.i_b8_cloud, R.drawable.i_b8_fog, R.drawable.i_b8_drizzle, R.drawable.i_b8_rain, R.drawable.i_b8_snow, R.drawable.i_b8_storm),
        intArrayOf(R.drawable.i_c1_sun, R.drawable.i_c1_moon, R.drawable.i_c1_partly, R.drawable.i_c1_partly_night, R.drawable.i_c1_cloud, R.drawable.i_c1_fog, R.drawable.i_c1_drizzle, R.drawable.i_c1_rain, R.drawable.i_c1_snow, R.drawable.i_c1_storm),
        intArrayOf(R.drawable.i_c2_sun, R.drawable.i_c2_moon, R.drawable.i_c2_partly, R.drawable.i_c2_partly_night, R.drawable.i_c2_cloud, R.drawable.i_c2_fog, R.drawable.i_c2_drizzle, R.drawable.i_c2_rain, R.drawable.i_c2_snow, R.drawable.i_c2_storm),
        intArrayOf(R.drawable.i_c3_sun, R.drawable.i_c3_moon, R.drawable.i_c3_partly, R.drawable.i_c3_partly_night, R.drawable.i_c3_cloud, R.drawable.i_c3_fog, R.drawable.i_c3_drizzle, R.drawable.i_c3_rain, R.drawable.i_c3_snow, R.drawable.i_c3_storm),
        intArrayOf(R.drawable.i_c4_sun, R.drawable.i_c4_moon, R.drawable.i_c4_partly, R.drawable.i_c4_partly_night, R.drawable.i_c4_cloud, R.drawable.i_c4_fog, R.drawable.i_c4_drizzle, R.drawable.i_c4_rain, R.drawable.i_c4_snow, R.drawable.i_c4_storm),
        intArrayOf(R.drawable.i_c5_sun, R.drawable.i_c5_moon, R.drawable.i_c5_partly, R.drawable.i_c5_partly_night, R.drawable.i_c5_cloud, R.drawable.i_c5_fog, R.drawable.i_c5_drizzle, R.drawable.i_c5_rain, R.drawable.i_c5_snow, R.drawable.i_c5_storm),
        intArrayOf(R.drawable.i_c6_sun, R.drawable.i_c6_moon, R.drawable.i_c6_partly, R.drawable.i_c6_partly_night, R.drawable.i_c6_cloud, R.drawable.i_c6_fog, R.drawable.i_c6_drizzle, R.drawable.i_c6_rain, R.drawable.i_c6_snow, R.drawable.i_c6_storm),
        intArrayOf(R.drawable.i_c7_sun, R.drawable.i_c7_moon, R.drawable.i_c7_partly, R.drawable.i_c7_partly_night, R.drawable.i_c7_cloud, R.drawable.i_c7_fog, R.drawable.i_c7_drizzle, R.drawable.i_c7_rain, R.drawable.i_c7_snow, R.drawable.i_c7_storm),
        intArrayOf(R.drawable.i_c8_sun, R.drawable.i_c8_moon, R.drawable.i_c8_partly, R.drawable.i_c8_partly_night, R.drawable.i_c8_cloud, R.drawable.i_c8_fog, R.drawable.i_c8_drizzle, R.drawable.i_c8_rain, R.drawable.i_c8_snow, R.drawable.i_c8_storm),
        intArrayOf(R.drawable.i_d1_sun, R.drawable.i_d1_moon, R.drawable.i_d1_partly, R.drawable.i_d1_partly_night, R.drawable.i_d1_cloud, R.drawable.i_d1_fog, R.drawable.i_d1_drizzle, R.drawable.i_d1_rain, R.drawable.i_d1_snow, R.drawable.i_d1_storm),
        intArrayOf(R.drawable.i_d2_sun, R.drawable.i_d2_moon, R.drawable.i_d2_partly, R.drawable.i_d2_partly_night, R.drawable.i_d2_cloud, R.drawable.i_d2_fog, R.drawable.i_d2_drizzle, R.drawable.i_d2_rain, R.drawable.i_d2_snow, R.drawable.i_d2_storm),
        intArrayOf(R.drawable.i_d3_sun, R.drawable.i_d3_moon, R.drawable.i_d3_partly, R.drawable.i_d3_partly_night, R.drawable.i_d3_cloud, R.drawable.i_d3_fog, R.drawable.i_d3_drizzle, R.drawable.i_d3_rain, R.drawable.i_d3_snow, R.drawable.i_d3_storm),
        intArrayOf(R.drawable.i_d4_sun, R.drawable.i_d4_moon, R.drawable.i_d4_partly, R.drawable.i_d4_partly_night, R.drawable.i_d4_cloud, R.drawable.i_d4_fog, R.drawable.i_d4_drizzle, R.drawable.i_d4_rain, R.drawable.i_d4_snow, R.drawable.i_d4_storm),
        intArrayOf(R.drawable.i_d5_sun, R.drawable.i_d5_moon, R.drawable.i_d5_partly, R.drawable.i_d5_partly_night, R.drawable.i_d5_cloud, R.drawable.i_d5_fog, R.drawable.i_d5_drizzle, R.drawable.i_d5_rain, R.drawable.i_d5_snow, R.drawable.i_d5_storm),
        intArrayOf(R.drawable.i_d6_sun, R.drawable.i_d6_moon, R.drawable.i_d6_partly, R.drawable.i_d6_partly_night, R.drawable.i_d6_cloud, R.drawable.i_d6_fog, R.drawable.i_d6_drizzle, R.drawable.i_d6_rain, R.drawable.i_d6_snow, R.drawable.i_d6_storm),
        intArrayOf(R.drawable.i_d7_sun, R.drawable.i_d7_moon, R.drawable.i_d7_partly, R.drawable.i_d7_partly_night, R.drawable.i_d7_cloud, R.drawable.i_d7_fog, R.drawable.i_d7_drizzle, R.drawable.i_d7_rain, R.drawable.i_d7_snow, R.drawable.i_d7_storm),
        intArrayOf(R.drawable.i_d8_sun, R.drawable.i_d8_moon, R.drawable.i_d8_partly, R.drawable.i_d8_partly_night, R.drawable.i_d8_cloud, R.drawable.i_d8_fog, R.drawable.i_d8_drizzle, R.drawable.i_d8_rain, R.drawable.i_d8_snow, R.drawable.i_d8_storm),
        intArrayOf(R.drawable.r_sun, R.drawable.r_moon, R.drawable.r_partly, R.drawable.r_partly_night, R.drawable.r_cloud, R.drawable.r_fog, R.drawable.r_drizzle, R.drawable.r_rain, R.drawable.r_snow, R.drawable.r_storm)
    )
}
